apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy4672
  labels:
    app: autodeploy4672
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1720070389659
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy4672
  template:
    metadata:
      labels:
        app: autodeploy4672
    spec:
      containers:
        - name: autodeploy4672
          image: acrworkflow1720070389659.azurecr.io/image-workflow-1720070389659:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
